//! Userspace mirror types for eBPF map keys/values.
//!
//! Each mirror struct is a hand-written Rust definition of the corresponding
//! C struct (generated by libbpf-cargo into `src/bpf_rs/*.skel.rs`). Layouts
//! are pinned by layout consistency tests at the bottom of each submodule: if a C header
//! change drifts a size or field offset, `cargo test` fails loudly instead of
//! silently corrupting maps at runtime.
//!
//! Encoding/decoding goes through zerocopy derives. C unions are modeled as
//! raw byte arrays (e.g. `[u8; 16]`) because the union exactly overlays those
//! bytes, making the representations byte-for-byte equivalent. Implicit
//! padding is rejected by `IntoBytes`, so it must be spelled out explicitly
//! as `_pad` / `_pad_tail` fields.

use std::net::Ipv6Addr;

/// Typed accessors for the `u_inet_addr` / `u_inet6_addr` unions modeled as
/// `[u8; 16]`.
///
/// IPv4 reads/writes the `ip` variant (first 4 bytes, network order); IPv6
/// maps to the `bits` variant (all 16 bytes, network order).
pub(crate) trait Inet6Bytes: AsRef<[u8]> + AsMut<[u8]> {
    fn set_ipv4_be(&mut self, addr: u32) {
        self.as_mut()[..4].copy_from_slice(&addr.to_be_bytes());
    }

    #[cfg_attr(not(test), allow(dead_code))]
    fn ipv4(&self) -> u32 {
        u32::from_be_bytes(self.as_ref()[..4].try_into().unwrap())
    }

    fn set_ipv6(&mut self, addr: Ipv6Addr) {
        self.as_mut()[..16].copy_from_slice(&addr.octets());
    }
}

impl Inet6Bytes for [u8; 16] {}

/// Mirror and skel type sizes must match.
#[cfg(test)]
macro_rules! assert_size {
    ($mirror:ty, $skel:ty) => {
        assert_eq!(
            std::mem::size_of::<$mirror>(),
            std::mem::size_of::<$skel>(),
            concat!("size mismatch: ", stringify!($mirror), " vs ", stringify!($skel)),
        );
    };
}

/// Mirror and skel field offsets must match (nested paths supported).
#[cfg(test)]
macro_rules! assert_field {
    ($mirror:ty, $skel:ty, $($field:tt).+) => {
        assert_eq!(
            std::mem::offset_of!($mirror, $($field).+),
            std::mem::offset_of!($skel, $($field).+),
            concat!(
                "offset mismatch: ",
                stringify!($mirror),
                ".",
                stringify!($($field).+),
            ),
        );
    };
}

/// When field names differ (union modeling / nested flattening), specify the
/// mirror and skel field paths separately.
#[cfg(test)]
macro_rules! assert_field_as {
    ($mirror:ty, $($mfield:tt).+, $skel:ty, $($sfield:tt).+) => {
        assert_eq!(
            std::mem::offset_of!($mirror, $($mfield).+),
            std::mem::offset_of!($skel, $($sfield).+),
            concat!(
                "offset mismatch: ",
                stringify!($mirror),
                ".",
                stringify!($($mfield).+),
                " vs ",
                stringify!($skel),
                ".",
                stringify!($($sfield).+),
            ),
        );
    };
}

mod firewall;
mod flow;
mod mac;
mod metric;
mod nat;
mod route;
mod wan;

pub(crate) use firewall::*;
pub(crate) use flow::*;
pub(crate) use mac::*;
#[allow(unused_imports)]
pub(crate) use metric::*;
pub(crate) use nat::*;
pub(crate) use route::*;
pub(crate) use wan::*;

#[cfg(test)]
mod tests {
    use super::*;
    use zerocopy::IntoBytes;

    /// `Default` must yield all-zero bytes: keys built via
    /// `..Default::default()` rely on zeroed padding, and eBPF map lookups
    /// compare the full key — one stray non-zero byte silently misses.
    #[test]
    fn default_keys_are_all_zero() {
        macro_rules! assert_default_zero {
            ($($ty:ty),+ $(,)?) => {$(
                assert!(
                    <$ty as Default>::default().as_bytes().iter().all(|&b| b == 0),
                    concat!(stringify!($ty), ": Default leaves non-zero bytes"),
                );
            )+};
        }

        assert_default_zero!(
            MacKeyV4,
            MacKeyV6,
            WanIpInfoKey,
            Ipv4LpmKey,
            Ipv6LpmKey,
            FlowMatchKey,
            FlowDnsMatchKeyV4,
            FlowDnsMatchKeyV6,
            FlowIpTrieKeyV4,
            FlowIpTrieKeyV6,
            LanRouteKeyV4,
            LanRouteKeyV6,
            RtCacheKeyV4,
            RtCacheKeyV6,
            RouteTargetSlotKeyV4,
            RouteTargetSlotKeyV6,
            NetMetricKey,
            NatMappingKeyV4,
            StaticNat6MappingKey,
            Nat4TimerKey,
            Nat6TimerKey,
        );
    }
}
