[workspace.package]
version = "0.2.5"
edition = "2021"


[workspace]
members = [
    "landscape",
    "landscape-common",
    "landscape-dns",
    "landscape-ebpf",
    "landscape-webserver",
]

resolver = "2"
default-members = ["landscape-webserver"]


[workspace.dependencies]
const_format = "0.2.34"
sysinfo = "0.30.12"

once_cell = "*"
ctrlc = "3.2"
libc = "0.2.159"
libbpf-rs = { version = "0.24.8" }
libbpf-cargo = "0.24.8"
rand = "0.8.5"
serde = { version = "*", features = ["derive"] }
serde_json = { version = "1.0.117" }

rtnetlink = { version = "0.14.1" }
netlink-packet-route = { version = "0.19.0" }
netlink-packet-core = { version = "0.7.0" }

axum = { version = "0.7.7", features = ["ws"] }
axum-extra = { version = "0.9.4", features = ["typed-header"] }
netlink-sys = { version = "0.8.6" }
homedir = "0.3.3"
log = "0.4.22"
thiserror = "1.0.64"

toml_edit = "0.22.22"

tokio-util = { version = "0.7.0", features = ["codec", "net"] }

socket2 = "0.5.7"
regex = "*"

# for docker
bollard = "0.18.1"

[workspace.dependencies.tokio]
version = "1.38.0"

[workspace.dependencies.pnet]
version = "0.35.0"

[workspace.dependencies.clap]
version = "4.0.32"
default-features = false
features = ["std", "derive", "help", "usage", "env"]
