//! Per-domain eBPF map code: mirror types (`<domain>/types.rs`) plus runtime
//! map setting/syncing logic (`<domain>/setting.rs`).
//!
//! Mirror structs are hand-written Rust definitions of the corresponding C
//! structs (generated by libbpf-cargo into `src/bpf_rs/*.skel.rs`). Layouts are
//! pinned by layout consistency tests at the bottom of each `types.rs`: if a C
//! header change drifts a size or field offset, `cargo test` fails loudly
//! instead of silently corrupting maps at runtime.
//!
//! Encoding/decoding goes through zerocopy derives. C unions are modeled as
//! raw byte arrays (e.g. `[u8; 16]`) because the union exactly overlays those
//! bytes, making the representations byte-for-byte equivalent. Implicit
//! padding is rejected by `IntoBytes`, so it must be spelled out explicitly as
//! `_pad` / `_pad_tail` fields.
//!
//! The shared-map skeleton (`share_map.skel.rs`) and domain-agnostic helpers
//! (raw-byte map diffing, pinned-map reuse, `init_path`) live in this root
//! module.

use std::{collections::HashMap, mem::MaybeUninit, net::Ipv6Addr, path::Path};

use libbpf_rs::{
    skel::{OpenSkel, SkelBuilder},
    AsRawLibbpf, MapCore, MapFlags, OpenMapMut,
};

use crate::bpf_error::LdEbpfResult;
use crate::LandscapeMapPath;

/// Typed accessors for the `u_inet_addr` / `u_inet6_addr` unions modeled as
/// `[u8; 16]`.
///
/// IPv4 reads/writes the `ip` variant (first 4 bytes, network order); IPv6
/// maps to the `bits` variant (all 16 bytes, network order).
pub(crate) trait Inet6Bytes: AsRef<[u8]> + AsMut<[u8]> {
    fn set_ipv4_be(&mut self, addr: u32) {
        self.as_mut()[..4].copy_from_slice(&addr.to_be_bytes());
    }

    #[cfg_attr(not(test), allow(dead_code))]
    fn ipv4(&self) -> u32 {
        u32::from_be_bytes(self.as_ref()[..4].try_into().unwrap())
    }

    fn set_ipv6(&mut self, addr: Ipv6Addr) {
        self.as_mut()[..16].copy_from_slice(&addr.octets());
    }
}

impl Inet6Bytes for [u8; 16] {}

/// Mirror and skel type sizes must match.
#[cfg(test)]
macro_rules! assert_size {
    ($mirror:ty, $skel:ty) => {
        assert_eq!(
            std::mem::size_of::<$mirror>(),
            std::mem::size_of::<$skel>(),
            concat!("size mismatch: ", stringify!($mirror), " vs ", stringify!($skel)),
        );
    };
}

/// Mirror and skel field offsets must match (nested paths supported).
#[cfg(test)]
macro_rules! assert_field {
    ($mirror:ty, $skel:ty, $($field:tt).+) => {
        assert_eq!(
            std::mem::offset_of!($mirror, $($field).+),
            std::mem::offset_of!($skel, $($field).+),
            concat!(
                "offset mismatch: ",
                stringify!($mirror),
                ".",
                stringify!($($field).+),
            ),
        );
    };
}

/// When field names differ (union modeling / nested flattening), specify the
/// mirror and skel field paths separately.
#[cfg(test)]
macro_rules! assert_field_as {
    ($mirror:ty, $($mfield:tt).+, $skel:ty, $($sfield:tt).+) => {
        assert_eq!(
            std::mem::offset_of!($mirror, $($mfield).+),
            std::mem::offset_of!($skel, $($sfield).+),
            concat!(
                "offset mismatch: ",
                stringify!($mirror),
                ".",
                stringify!($($mfield).+),
                " vs ",
                stringify!($skel),
                ".",
                stringify!($($sfield).+),
            ),
        );
    };
}

pub mod dns;
pub mod firewall;
pub mod flow;
pub mod flow_dns;
pub mod flow_wanip;
pub mod mac;
pub mod metric;
pub mod nat;
pub mod redirect_able;
pub mod route;
pub mod wan;

/// Only referenced by the aggregated layout tests in this module.
#[cfg_attr(not(test), allow(unused_imports))]
pub(crate) use firewall::types::*;
/// Crate-wide convenience re-exports of mirror types (flat, like the former
/// `map_types` root). Prefer the per-domain path when importing in new code.
pub(crate) use flow::types::*;
pub(crate) use flow_dns::types::*;
pub(crate) use flow_wanip::types::*;
pub(crate) use mac::types::*;
/// Only referenced by the aggregated layout tests in this module.
#[cfg_attr(not(test), allow(unused_imports))]
pub(crate) use metric::types::*;
pub(crate) use nat::types::*;
pub(crate) use route::types::*;
/// Only referenced by the aggregated layout tests in this module.
#[cfg_attr(not(test), allow(unused_imports))]
pub(crate) use wan::types::*;

pub type RawEbpfMapEntries = HashMap<Vec<u8>, Vec<u8>>;

pub(crate) struct RawEbpfMapDiff {
    pub delete_keys: Vec<Vec<u8>>,
    pub upsert_entries: Vec<(Vec<u8>, Vec<u8>)>,
}

impl RawEbpfMapDiff {
    pub fn is_empty(&self) -> bool {
        self.delete_keys.is_empty() && self.upsert_entries.is_empty()
    }
}

pub(crate) fn snapshot_raw_map<M: MapCore>(map: &M) -> LdEbpfResult<RawEbpfMapEntries> {
    let mut result = RawEbpfMapEntries::new();
    for key in map.keys() {
        if let Some(value) = map.lookup(&key, MapFlags::ANY)? {
            result.insert(key, value);
        }
    }
    Ok(result)
}

pub(crate) fn diff_raw_map(
    current: &RawEbpfMapEntries,
    desired: &RawEbpfMapEntries,
) -> RawEbpfMapDiff {
    let delete_keys = current.keys().filter(|key| !desired.contains_key(*key)).cloned().collect();

    let upsert_entries = desired
        .iter()
        .filter(|(key, value)| current.get(*key) != Some(*value))
        .map(|(key, value)| (key.clone(), value.clone()))
        .collect();

    RawEbpfMapDiff { delete_keys, upsert_entries }
}

pub(crate) fn apply_raw_map_diff<M: MapCore>(map: &M, diff: RawEbpfMapDiff) -> LdEbpfResult<()> {
    if !diff.delete_keys.is_empty() {
        let key_count = diff.delete_keys.len() as u32;
        let mut keys = Vec::with_capacity(diff.delete_keys.iter().map(Vec::len).sum());
        for key in diff.delete_keys {
            keys.extend_from_slice(&key);
        }
        map.delete_batch(&keys, key_count, MapFlags::ANY, MapFlags::ANY)?;
    }

    if !diff.upsert_entries.is_empty() {
        let entry_count = diff.upsert_entries.len() as u32;
        let key_len: usize = diff.upsert_entries.iter().map(|(key, _)| key.len()).sum();
        let value_len: usize = diff.upsert_entries.iter().map(|(_, value)| value.len()).sum();
        let mut keys = Vec::with_capacity(key_len);
        let mut values = Vec::with_capacity(value_len);
        for (key, value) in diff.upsert_entries {
            keys.extend_from_slice(&key);
            values.extend_from_slice(&value);
        }
        map.update_batch(&keys, &values, entry_count, MapFlags::ANY, MapFlags::ANY)?;
    }

    Ok(())
}

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum PinnedMapReuseStatus {
    Compatible,
    Missing,
    Incompatible,
}

pub fn probe_pinned_map_reuse(
    map: &mut OpenMapMut,
    path: &(impl AsRef<Path> + ?Sized),
) -> PinnedMapReuseStatus {
    let ptr = map.as_libbpf_object().as_ptr();
    let expected_ty = unsafe { libbpf_rs::libbpf_sys::bpf_map__type(ptr) };
    let expected_ks = unsafe { libbpf_rs::libbpf_sys::bpf_map__key_size(ptr) };
    let expected_vs = unsafe { libbpf_rs::libbpf_sys::bpf_map__value_size(ptr) };
    let expected_me = unsafe { libbpf_rs::libbpf_sys::bpf_map__max_entries(ptr) };
    let expected_flags = unsafe { libbpf_rs::libbpf_sys::bpf_map__map_flags(ptr) };
    map.set_pin_path(path).unwrap();
    if !path.as_ref().exists() {
        return PinnedMapReuseStatus::Missing;
    }
    let pinned = match libbpf_rs::MapHandle::from_pinned_path(path) {
        Ok(pinned) => pinned,
        Err(e) => {
            tracing::warn!(
                "Cannot inspect pinned map {}: {e}, will recreate",
                path.as_ref().display(),
            );
            return PinnedMapReuseStatus::Incompatible;
        }
    };
    let pinned_info = match pinned.info() {
        Ok(info) => info,
        Err(e) => {
            tracing::warn!(
                "Cannot inspect pinned map {} info: {e}, will recreate",
                path.as_ref().display(),
            );
            return PinnedMapReuseStatus::Incompatible;
        }
    };
    let actual_ty = pinned.map_type() as u32;
    let actual_ks = pinned.key_size();
    let actual_vs = pinned.value_size();
    let actual_me = pinned.max_entries();
    let actual_flags = pinned_info.info.map_flags;

    if actual_ty != expected_ty
        || actual_ks != expected_ks
        || actual_vs != expected_vs
        || actual_me != expected_me
        || actual_flags != expected_flags
    {
        tracing::warn!(
            "Pinned map {} layout changed (type {}->{}, ks {}->{}, vs {}->{}, max_entries {}->{}, flags {:#x}->{:#x}), will recreate",
            path.as_ref().display(),
            actual_ty,
            expected_ty,
            actual_ks,
            expected_ks,
            actual_vs,
            expected_vs,
            actual_me,
            expected_me,
            actual_flags,
            expected_flags,
        );
        return PinnedMapReuseStatus::Incompatible;
    }

    PinnedMapReuseStatus::Compatible
}

/// Try to reuse a pinned map. If the pinned map is incompatible (e.g. struct
/// layout changed), remove the stale pin file so `load()` creates a fresh one.
///
/// NOTE: libbpf's `bpf_map__reuse_fd` silently overwrites the map definition
/// with the reused fd's sizes, so we must check key/value sizes explicitly
/// before calling `reuse_pinned_map`.
pub fn reuse_pinned_map_or_recreate(map: &mut OpenMapMut, path: &(impl AsRef<Path> + ?Sized)) {
    match probe_pinned_map_reuse(map, path) {
        PinnedMapReuseStatus::Compatible => {
            if let Err(e) = map.reuse_pinned_map(path) {
                tracing::warn!(
                    "Pinned map {} reuse failed: {e}, will recreate",
                    path.as_ref().display(),
                );
                let _ = std::fs::remove_file(path);
            }
        }
        PinnedMapReuseStatus::Missing => {}
        PinnedMapReuseStatus::Incompatible => {
            let _ = std::fs::remove_file(path);
        }
    }
}

pub(crate) mod share_map {
    include!(concat!(env!("CARGO_MANIFEST_DIR"), "/src/bpf_rs/share_map.skel.rs"));
}

use share_map::*;

pub(crate) fn init_path(paths: &LandscapeMapPath) {
    let landscape_builder = ShareMapSkelBuilder::default();
    // landscape_builder.obj_builder.debug(true);
    let mut open_object = MaybeUninit::uninit();
    let mut landscape_open = crate::bpf_ctx!(
        landscape_builder.open(&mut open_object),
        "maps open shared maps skeleton failed"
    )
    .unwrap();

    reuse_pinned_map_or_recreate(&mut landscape_open.maps.wan_ip_binding, &paths.wan_ip);
    // NAT
    reuse_pinned_map_or_recreate(&mut landscape_open.maps.nat6_static_map, &paths.nat6_static_map);
    reuse_pinned_map_or_recreate(&mut landscape_open.maps.nat4_static_map, &paths.nat4_static_map);

    // firewall
    reuse_pinned_map_or_recreate(
        &mut landscape_open.maps.firewall_block_ip4_map,
        &paths.firewall_ipv4_block,
    );
    reuse_pinned_map_or_recreate(
        &mut landscape_open.maps.firewall_block_ip6_map,
        &paths.firewall_ipv6_block,
    );
    reuse_pinned_map_or_recreate(&mut landscape_open.maps.flow_match_map, &paths.flow_match_map);
    reuse_pinned_map_or_recreate(&mut landscape_open.maps.dns_flow_socks, &paths.dns_flow_socks);

    // metric
    reuse_pinned_map_or_recreate(&mut landscape_open.maps.metric_bucket_map, &paths.metric_map);
    reuse_pinned_map_or_recreate(
        &mut landscape_open.maps.nat_metric_events,
        &paths.nat_metric_events,
    );
    reuse_pinned_map_or_recreate(
        &mut landscape_open.maps.firewall_conn_metric_events,
        &paths.firewall_conn_metric_events,
    );

    let _ = std::fs::remove_file(&paths.rt4_lan_map);
    let _ = std::fs::remove_file(&paths.rt6_lan_map);
    let _ = std::fs::remove_file(&paths.rt4_target_slot_map);
    let _ = std::fs::remove_file(&paths.rt6_target_slot_map);

    // flow verdict and forward
    reuse_pinned_map_or_recreate(&mut landscape_open.maps.rt4_lan_map, &paths.rt4_lan_map);
    reuse_pinned_map_or_recreate(
        &mut landscape_open.maps.rt4_target_slot_map,
        &paths.rt4_target_slot_map,
    );
    reuse_pinned_map_or_recreate(&mut landscape_open.maps.flow4_dns_map, &paths.flow4_dns_map);
    reuse_pinned_map_or_recreate(&mut landscape_open.maps.flow4_ip_map, &paths.flow4_ip_map);

    reuse_pinned_map_or_recreate(&mut landscape_open.maps.rt6_lan_map, &paths.rt6_lan_map);
    reuse_pinned_map_or_recreate(
        &mut landscape_open.maps.rt6_target_slot_map,
        &paths.rt6_target_slot_map,
    );
    reuse_pinned_map_or_recreate(&mut landscape_open.maps.flow6_dns_map, &paths.flow6_dns_map);
    reuse_pinned_map_or_recreate(&mut landscape_open.maps.flow6_ip_map, &paths.flow6_ip_map);

    // 每次启动重建 cache 外层 map（含内层 map），避免结构体变更后大小不匹配。
    let _ = std::fs::remove_file(&paths.rt4_cache_map);
    let _ = std::fs::remove_file(&paths.rt6_cache_map);

    reuse_pinned_map_or_recreate(&mut landscape_open.maps.rt4_cache_map, &paths.rt4_cache_map);
    reuse_pinned_map_or_recreate(&mut landscape_open.maps.rt6_cache_map, &paths.rt6_cache_map);

    reuse_pinned_map_or_recreate(&mut landscape_open.maps.ip_mac_v4, &paths.ip_mac_v4);
    reuse_pinned_map_or_recreate(&mut landscape_open.maps.ip_mac_v6, &paths.ip_mac_v6);
    reuse_pinned_map_or_recreate(&mut landscape_open.maps.ip6_dao_events, &paths.ip6_dao_events);
    reuse_pinned_map_or_recreate(
        &mut landscape_open.maps.xdp_redirect_able,
        &paths.xdp_redirect_able,
    );

    let _landscape_skel =
        crate::bpf_ctx!(landscape_open.load(), "maps load shared maps skeleton failed").unwrap();
    route::cache::init_route_wan_cache_inner_map(paths);
    route::cache::init_route_lan_cache_inner_map(paths);
}

/// Unpin shared maps during full app shutdown so the kernel can free them.
///
/// Must be called after all services have stopped.
pub fn cleanup_pinned_maps() {
    let maps_to_unpin: [&std::path::Path; 0] = [];
    for path in maps_to_unpin {
        match std::fs::remove_file(path) {
            Ok(()) => tracing::info!("Unpinned map: {}", path.display()),
            Err(e) if e.kind() == std::io::ErrorKind::NotFound => {}
            Err(e) => tracing::warn!("Failed to unpin {}: {e}", path.display()),
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use zerocopy::IntoBytes;

    /// `Default` must yield all-zero bytes: keys built via
    /// `..Default::default()` rely on zeroed padding, and eBPF map lookups
    /// compare the full key — one stray non-zero byte silently misses.
    #[test]
    fn default_keys_are_all_zero() {
        macro_rules! assert_default_zero {
            ($($ty:ty),+ $(,)?) => {$(
                assert!(
                    <$ty as Default>::default().as_bytes().iter().all(|&b| b == 0),
                    concat!(stringify!($ty), ": Default leaves non-zero bytes"),
                );
            )+};
        }

        assert_default_zero!(
            MacKeyV4,
            MacKeyV6,
            WanIpInfoKey,
            Ipv4LpmKey,
            Ipv6LpmKey,
            FlowMatchKey,
            FlowDnsMatchKeyV4,
            FlowDnsMatchKeyV6,
            FlowIpTrieKeyV4,
            FlowIpTrieKeyV6,
            LanRouteKeyV4,
            LanRouteKeyV6,
            RtCacheKeyV4,
            RtCacheKeyV6,
            RouteTargetSlotKeyV4,
            RouteTargetSlotKeyV6,
            NetMetricKey,
            NatMappingKeyV4,
            StaticNat6MappingKey,
            Nat4TimerKey,
            Nat6TimerKey,
        );
    }
}
