//! Per-domain eBPF map code: mirror types (`<domain>/types.rs`), runtime map
//! setting/syncing logic (`<domain>/setting.rs`) and startup map
//! creation/pinning (`<domain>/init.rs`).
//!
//! Mirror structs are hand-written Rust definitions of the corresponding C
//! structs (generated by libbpf-cargo into `src/bpf_rs/*.skel.rs`). Layouts are
//! pinned by layout consistency tests at the bottom of each `types.rs`: if a C
//! header change drifts a size or field offset, `cargo test` fails loudly
//! instead of silently corrupting maps at runtime.
//!
//! Encoding/decoding goes through zerocopy derives. C unions are modeled as
//! raw byte arrays (e.g. `[u8; 16]`) because the union exactly overlays those
//! bytes, making the representations byte-for-byte equivalent. Implicit
//! padding is rejected by `IntoBytes`, so it must be spelled out explicitly as
//! `_pad` / `_pad_tail` fields.
//!
//! Shared maps are created and pinned directly from Rust (`bpf_map_create`,
//! no C skeleton) by the per-domain `<domain>/init.rs` modules, orchestrated
//! from [`init_path`]. Every BPF program still declares its own copy of the
//! shared map (C headers) and reuses the pinned map on load, so the creation
//! parameters must stay in lockstep with the C definitions — the per-domain
//! `init.rs` tests compare them against the real skeleton map defs.
//!
//! Domain-agnostic helpers (raw-byte map diffing, pinned-map reuse, map
//! creation specs) live in this root module.

use std::{
    collections::HashMap,
    net::Ipv6Addr,
    os::fd::{AsFd, AsRawFd},
    path::Path,
};

use libbpf_rs::{AsRawLibbpf, MapCore, MapFlags, MapHandle, MapType, OpenMapMut};

use crate::bpf_error::LdEbpfResult;
use crate::LandscapeMapPath;

/// Typed accessors for the `u_inet_addr` / `u_inet6_addr` unions modeled as
/// `[u8; 16]`.
///
/// IPv4 reads/writes the `ip` variant (first 4 bytes, network order); IPv6
/// maps to the `bits` variant (all 16 bytes, network order).
pub(crate) trait Inet6Bytes: AsRef<[u8]> + AsMut<[u8]> {
    fn set_ipv4_be(&mut self, addr: u32) {
        self.as_mut()[..4].copy_from_slice(&addr.to_be_bytes());
    }

    #[cfg_attr(not(test), allow(dead_code))]
    fn ipv4(&self) -> u32 {
        u32::from_be_bytes(self.as_ref()[..4].try_into().unwrap())
    }

    fn set_ipv6(&mut self, addr: Ipv6Addr) {
        self.as_mut()[..16].copy_from_slice(&addr.octets());
    }
}

impl Inet6Bytes for [u8; 16] {}

/// Mirror and skel type sizes must match.
#[cfg(test)]
macro_rules! assert_size {
    ($mirror:ty, $skel:ty) => {
        assert_eq!(
            std::mem::size_of::<$mirror>(),
            std::mem::size_of::<$skel>(),
            concat!("size mismatch: ", stringify!($mirror), " vs ", stringify!($skel)),
        );
    };
}

/// Mirror and skel field offsets must match (nested paths supported).
#[cfg(test)]
macro_rules! assert_field {
    ($mirror:ty, $skel:ty, $($field:tt).+) => {
        assert_eq!(
            std::mem::offset_of!($mirror, $($field).+),
            std::mem::offset_of!($skel, $($field).+),
            concat!(
                "offset mismatch: ",
                stringify!($mirror),
                ".",
                stringify!($($field).+),
            ),
        );
    };
}

/// When field names differ (union modeling / nested flattening), specify the
/// mirror and skel field paths separately.
#[cfg(test)]
macro_rules! assert_field_as {
    ($mirror:ty, $($mfield:tt).+, $skel:ty, $($sfield:tt).+) => {
        assert_eq!(
            std::mem::offset_of!($mirror, $($mfield).+),
            std::mem::offset_of!($skel, $($sfield).+),
            concat!(
                "offset mismatch: ",
                stringify!($mirror),
                ".",
                stringify!($($mfield).+),
                " vs ",
                stringify!($skel),
                ".",
                stringify!($($sfield).+),
            ),
        );
    };
}

pub mod dns;
pub mod firewall;
pub mod flow;
pub mod flow_dns;
pub mod flow_wanip;
pub mod mac;
pub mod nat;
pub mod redirect_able;
pub mod route;
pub mod wan;

/// Only referenced by the aggregated layout tests in this module.
#[cfg_attr(not(test), allow(unused_imports))]
pub(crate) use firewall::types::*;
/// Crate-wide convenience re-exports of mirror types (flat, like the former
/// `map_types` root). Prefer the per-domain path when importing in new code.
pub(crate) use flow::types::*;
pub(crate) use flow_dns::types::*;
pub(crate) use flow_wanip::types::*;
pub(crate) use mac::types::*;
pub(crate) use nat::types::*;
pub(crate) use route::types::*;
/// Only referenced by the aggregated layout tests in this module.
#[cfg_attr(not(test), allow(unused_imports))]
pub(crate) use wan::types::*;

pub type RawEbpfMapEntries = HashMap<Vec<u8>, Vec<u8>>;

pub(crate) struct RawEbpfMapDiff {
    pub delete_keys: Vec<Vec<u8>>,
    pub upsert_entries: Vec<(Vec<u8>, Vec<u8>)>,
}

impl RawEbpfMapDiff {
    pub fn is_empty(&self) -> bool {
        self.delete_keys.is_empty() && self.upsert_entries.is_empty()
    }
}

pub(crate) fn snapshot_raw_map<M: MapCore>(map: &M) -> LdEbpfResult<RawEbpfMapEntries> {
    let mut result = RawEbpfMapEntries::new();
    for key in map.keys() {
        if let Some(value) = map.lookup(&key, MapFlags::ANY)? {
            result.insert(key, value);
        }
    }
    Ok(result)
}

pub(crate) fn diff_raw_map(
    current: &RawEbpfMapEntries,
    desired: &RawEbpfMapEntries,
) -> RawEbpfMapDiff {
    let delete_keys = current.keys().filter(|key| !desired.contains_key(*key)).cloned().collect();

    let upsert_entries = desired
        .iter()
        .filter(|(key, value)| current.get(*key) != Some(*value))
        .map(|(key, value)| (key.clone(), value.clone()))
        .collect();

    RawEbpfMapDiff { delete_keys, upsert_entries }
}

pub(crate) fn apply_raw_map_diff<M: MapCore>(map: &M, diff: RawEbpfMapDiff) -> LdEbpfResult<()> {
    if !diff.delete_keys.is_empty() {
        let key_count = diff.delete_keys.len() as u32;
        let mut keys = Vec::with_capacity(diff.delete_keys.iter().map(Vec::len).sum());
        for key in diff.delete_keys {
            keys.extend_from_slice(&key);
        }
        map.delete_batch(&keys, key_count, MapFlags::ANY, MapFlags::ANY)?;
    }

    if !diff.upsert_entries.is_empty() {
        let entry_count = diff.upsert_entries.len() as u32;
        let key_len: usize = diff.upsert_entries.iter().map(|(key, _)| key.len()).sum();
        let value_len: usize = diff.upsert_entries.iter().map(|(_, value)| value.len()).sum();
        let mut keys = Vec::with_capacity(key_len);
        let mut values = Vec::with_capacity(value_len);
        for (key, value) in diff.upsert_entries {
            keys.extend_from_slice(&key);
            values.extend_from_slice(&value);
        }
        map.update_batch(&keys, &values, entry_count, MapFlags::ANY, MapFlags::ANY)?;
    }

    Ok(())
}

/// Create-opts plumbing for skeleton-free shared maps (`<domain>/init.rs`).
///
/// Each `init` module declares one [`MapCreateSpec`] per C `SEC(".maps")`
/// definition it must reproduce, then calls [`ensure_pinned_map`] /
/// [`recreate_pinned_map`]. The specs are also reused by the `#[cfg(test)]`
/// consistency tests that diff them against the real skel map defs.
#[derive(Debug, Clone, Copy)]
pub(crate) struct MapCreateSpec {
    pub map_type: MapType,
    /// Kernel map name. Matches the C symbol name; libbpf truncates names
    /// longer than `BPF_OBJ_NAME_LEN - 1` at create time, same as it does for
    /// skeleton maps.
    pub name: &'static str,
    pub key_size: u32,
    pub value_size: u32,
    pub max_entries: u32,
    pub map_flags: u32,
    /// Inner-map template for map-in-map outer maps (HASH_OF_MAPS /
    /// ARRAY_OF_MAPS). The template map is created transiently and only used
    /// to bind the kernel-side inner map type; it is never pinned.
    pub inner: Option<InnerMapSpec>,
}

/// Inner-map template params for a map-in-map [`MapCreateSpec`] (matches the
/// `struct each_*` / `__array(values, ...)` template in the C header).
#[derive(Debug, Clone, Copy)]
pub(crate) struct InnerMapSpec {
    pub map_type: MapType,
    pub name: &'static str,
    pub key_size: u32,
    pub value_size: u32,
    pub max_entries: u32,
    pub map_flags: u32,
}

impl MapCreateSpec {
    /// True when an existing pinned map is still usable: same type, key/value
    /// sizes, max entries and map flags as this spec (mirrors the checks done
    /// by [`probe_pinned_map_reuse`]).
    ///
    /// Map-in-map outers (specs with `inner: Some(..)`) are **never** reused:
    /// a pinned `MapHandle` does not expose the kernel-side inner map template,
    /// so the only way to guarantee the inner template matches this spec is to
    /// recreate the outer map on every start (the same policy the route verdict
    /// caches already use).
    fn matches_pinned(&self, pinned: &MapHandle) -> bool {
        if self.inner.is_some() {
            tracing::warn!(
                "pinned map {} (name `{}`) is a map-in-map outer; recreating to guarantee the inner template matches",
                pinned.name().to_string_lossy(),
                self.name
            );
            return false;
        }
        if pinned.map_type() != self.map_type
            || pinned.key_size() != self.key_size
            || pinned.value_size() != self.value_size
            || pinned.max_entries() != self.max_entries
        {
            return false;
        }
        match libbpf_rs::MapInfo::new(pinned.as_fd()) {
            Ok(info) => info.info.map_flags == self.map_flags,
            Err(e) => {
                tracing::warn!(
                    "cannot inspect pinned map {} info: {e}",
                    pinned.name().to_string_lossy()
                );
                false
            }
        }
    }
}

fn map_create_opts(map_flags: u32, inner_map_fd: Option<i32>) -> libbpf_sys::bpf_map_create_opts {
    #[allow(clippy::needless_update)]
    let mut opts = libbpf_sys::bpf_map_create_opts {
        sz: std::mem::size_of::<libbpf_sys::bpf_map_create_opts>() as libbpf_sys::size_t,
        ..Default::default()
    };
    opts.map_flags = map_flags;
    if let Some(fd) = inner_map_fd {
        opts.inner_map_fd = fd as u32;
    }
    opts
}

/// Create the kernel map (and its transient inner-map template, if any)
/// without loading any skeleton.
fn create_map_handle(spec: &MapCreateSpec) -> LdEbpfResult<MapHandle> {
    // Keep the template map alive until `bpf_map_create` has bound the inner
    // type (the kernel resolves `inner_map_fd` while creating the outer map).
    let mut inner_template: Option<MapHandle> = None;
    let inner_fd = match &spec.inner {
        Some(inner) => {
            let opts = map_create_opts(inner.map_flags, None);
            let inner_map = crate::bpf_ctx!(
                MapHandle::create(
                    inner.map_type,
                    Some(inner.name),
                    inner.key_size,
                    inner.value_size,
                    inner.max_entries,
                    &opts,
                ),
                "create inner template map `{}` failed",
                inner.name
            )?;
            let fd = inner_map.as_fd().as_raw_fd();
            inner_template = Some(inner_map);
            Some(fd)
        }
        None => None,
    };

    let opts = map_create_opts(spec.map_flags, inner_fd);
    let map = crate::bpf_ctx!(
        MapHandle::create(
            spec.map_type,
            Some(spec.name),
            spec.key_size,
            spec.value_size,
            spec.max_entries,
            &opts,
        ),
        "create map `{}` failed",
        spec.name
    )?;
    drop(inner_template);
    Ok(map)
}

fn pin_new_map(spec: &MapCreateSpec, path: &Path) -> LdEbpfResult<MapHandle> {
    let mut map = create_map_handle(spec)?;
    crate::bpf_ctx!(map.pin(path), "pin map `{}` at {} failed", spec.name, path.display())?;
    Ok(map)
}

/// Drop a stale pin file, ignoring a missing file.
fn remove_pin_file(path: &Path) {
    match std::fs::remove_file(path) {
        Ok(()) => {}
        Err(e) if e.kind() == std::io::ErrorKind::NotFound => {}
        Err(e) => tracing::warn!("failed to remove stale pin file {}: {e}", path.display()),
    }
}

/// Reuse the pinned map at `path` if it still matches `spec` (keeps existing
/// entries across restarts); otherwise remove the stale pin file and create a
/// fresh map pinned at `path`.
pub(crate) fn ensure_pinned_map(spec: &MapCreateSpec, path: &Path) -> LdEbpfResult<MapHandle> {
    if path.exists() {
        match MapHandle::from_pinned_path(path) {
            Ok(pinned) => {
                if spec.matches_pinned(&pinned) {
                    return Ok(pinned);
                }
                tracing::warn!(
                    "pinned map {} (name `{}`) no longer matches spec, will recreate",
                    path.display(),
                    spec.name
                );
                remove_pin_file(path);
            }
            Err(e) => {
                tracing::warn!("cannot open pinned map {}: {e}, will recreate", path.display());
                remove_pin_file(path);
            }
        }
    }
    pin_new_map(spec, path)
}

/// Always recreate the map: remove the pin file (any existing data is
/// intentionally dropped, e.g. per-boot route verdict caches) then create and
/// pin a fresh map.
pub(crate) fn recreate_pinned_map(spec: &MapCreateSpec, path: &Path) -> LdEbpfResult<MapHandle> {
    remove_pin_file(path);
    pin_new_map(spec, path)
}

/// Diff a real skel map definition against a Rust [`MapCreateSpec`]. Used by
/// the per-domain `init.rs` tests to prove the Rust creation parameters stay
/// in lockstep with the C headers the BPF programs compile against.
#[cfg(test)]
pub(crate) fn assert_skel_map_matches(map: &OpenMapMut<'_>, spec: &MapCreateSpec) {
    let ptr = map.as_libbpf_object().as_ptr();
    let actual_ty = unsafe { libbpf_sys::bpf_map__type(ptr) };
    let actual_ks = unsafe { libbpf_sys::bpf_map__key_size(ptr) };
    let actual_vs = unsafe { libbpf_sys::bpf_map__value_size(ptr) };
    let actual_me = unsafe { libbpf_sys::bpf_map__max_entries(ptr) };
    let actual_flags = unsafe { libbpf_sys::bpf_map__map_flags(ptr) };

    let name = spec.name;
    assert_eq!(actual_ty, spec.map_type as u32, "map `{name}`: type drift");
    assert_eq!(actual_ks, spec.key_size, "map `{name}`: key size drift");
    assert_eq!(actual_vs, spec.value_size, "map `{name}`: value size drift");
    assert_eq!(actual_me, spec.max_entries, "map `{name}`: max_entries drift");
    assert_eq!(actual_flags, spec.map_flags, "map `{name}`: map_flags drift");

    match spec.inner {
        Some(inner) => {
            let inner_ptr = unsafe { libbpf_sys::bpf_map__inner_map(ptr) };
            assert!(
                !inner_ptr.is_null(),
                "map `{name}`: spec declares an inner template but the C definition is not a map-in-map"
            );
            let inner_ty = unsafe { libbpf_sys::bpf_map__type(inner_ptr) };
            let inner_ks = unsafe { libbpf_sys::bpf_map__key_size(inner_ptr) };
            let inner_vs = unsafe { libbpf_sys::bpf_map__value_size(inner_ptr) };
            let inner_me = unsafe { libbpf_sys::bpf_map__max_entries(inner_ptr) };
            let inner_flags = unsafe { libbpf_sys::bpf_map__map_flags(inner_ptr) };
            assert_eq!(inner_ty, inner.map_type as u32, "map `{name}`: inner type drift");
            assert_eq!(inner_ks, inner.key_size, "map `{name}`: inner key size drift");
            assert_eq!(inner_vs, inner.value_size, "map `{name}`: inner value size drift");
            assert_eq!(inner_me, inner.max_entries, "map `{name}`: inner max_entries drift");
            assert_eq!(inner_flags, inner.map_flags, "map `{name}`: inner map_flags drift");
        }
        None => {
            let inner_ptr = unsafe { libbpf_sys::bpf_map__inner_map(ptr) };
            assert!(
                inner_ptr.is_null(),
                "map `{name}`: spec declares no inner template but the C definition is a map-in-map"
            );
        }
    }
}

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum PinnedMapReuseStatus {
    Compatible,
    Missing,
    Incompatible,
}

pub fn probe_pinned_map_reuse(
    map: &mut OpenMapMut,
    path: &(impl AsRef<Path> + ?Sized),
) -> PinnedMapReuseStatus {
    let ptr = map.as_libbpf_object().as_ptr();
    let expected_ty = unsafe { libbpf_rs::libbpf_sys::bpf_map__type(ptr) };
    let expected_ks = unsafe { libbpf_rs::libbpf_sys::bpf_map__key_size(ptr) };
    let expected_vs = unsafe { libbpf_rs::libbpf_sys::bpf_map__value_size(ptr) };
    let expected_me = unsafe { libbpf_rs::libbpf_sys::bpf_map__max_entries(ptr) };
    let expected_flags = unsafe { libbpf_rs::libbpf_sys::bpf_map__map_flags(ptr) };
    map.set_pin_path(path).unwrap();
    if !path.as_ref().exists() {
        return PinnedMapReuseStatus::Missing;
    }
    let pinned = match libbpf_rs::MapHandle::from_pinned_path(path) {
        Ok(pinned) => pinned,
        Err(e) => {
            tracing::warn!(
                "Cannot inspect pinned map {}: {e}, will recreate",
                path.as_ref().display(),
            );
            return PinnedMapReuseStatus::Incompatible;
        }
    };
    let pinned_info = match pinned.info() {
        Ok(info) => info,
        Err(e) => {
            tracing::warn!(
                "Cannot inspect pinned map {} info: {e}, will recreate",
                path.as_ref().display(),
            );
            return PinnedMapReuseStatus::Incompatible;
        }
    };
    let actual_ty = pinned.map_type() as u32;
    let actual_ks = pinned.key_size();
    let actual_vs = pinned.value_size();
    let actual_me = pinned.max_entries();
    let actual_flags = pinned_info.info.map_flags;

    if actual_ty != expected_ty
        || actual_ks != expected_ks
        || actual_vs != expected_vs
        || actual_me != expected_me
        || actual_flags != expected_flags
    {
        tracing::warn!(
            "Pinned map {} layout changed (type {}->{}, ks {}->{}, vs {}->{}, max_entries {}->{}, flags {:#x}->{:#x}), will recreate",
            path.as_ref().display(),
            actual_ty,
            expected_ty,
            actual_ks,
            expected_ks,
            actual_vs,
            expected_vs,
            actual_me,
            expected_me,
            actual_flags,
            expected_flags,
        );
        return PinnedMapReuseStatus::Incompatible;
    }

    PinnedMapReuseStatus::Compatible
}

/// Try to reuse a pinned map. If the pinned map is incompatible (e.g. struct
/// layout changed), remove the stale pin file so `load()` creates a fresh one.
///
/// NOTE: libbpf's `bpf_map__reuse_fd` silently overwrites the map definition
/// with the reused fd's sizes, so we must check key/value sizes explicitly
/// before calling `reuse_pinned_map`.
pub fn reuse_pinned_map_or_recreate(map: &mut OpenMapMut, path: &(impl AsRef<Path> + ?Sized)) {
    match probe_pinned_map_reuse(map, path) {
        PinnedMapReuseStatus::Compatible => {
            if let Err(e) = map.reuse_pinned_map(path) {
                tracing::warn!(
                    "Pinned map {} reuse failed: {e}, will recreate",
                    path.as_ref().display(),
                );
                let _ = std::fs::remove_file(path);
            }
        }
        PinnedMapReuseStatus::Missing => {}
        PinnedMapReuseStatus::Incompatible => {
            let _ = std::fs::remove_file(path);
        }
    }
}

/// Create/pin every shared map for the running daemon, before any BPF
/// program loads. Programs declare their own copy of each map in C and reuse
/// the pins below on load (`landscape::pin_and_reuse_map` /
/// `reuse_pinned_map_or_recreate`).
///
/// Per-map behavior is defined in the per-domain `<domain>/init.rs` modules:
/// persistent maps (`ensure_pinned_map`) keep their data across restarts
/// while layout drifts trigger a recreate; per-boot maps
/// (`recreate_pinned_map`) are dropped and rebuilt on every start.
pub(crate) fn init_path(paths: &LandscapeMapPath) {
    // WAN
    wan::init_wan_ip_binding_map(&paths.wan_ip).expect("init wan_ip_binding failed");
    // NAT
    nat::init_nat6_static_map(&paths.nat6_static_map).expect("init nat6_static_map failed");
    nat::init_nat4_static_map(&paths.nat4_static_map).expect("init nat4_static_map failed");
    nat::init_nat_metric_events(&paths.nat_metric_events).expect("init nat_metric_events failed");

    // firewall
    firewall::init_firewall_block_ip4_map(&paths.firewall_ipv4_block)
        .expect("init firewall_block_ip4_map failed");
    firewall::init_firewall_block_ip6_map(&paths.firewall_ipv6_block)
        .expect("init firewall_block_ip6_map failed");
    firewall::init_firewall_conn_metric_events(&paths.firewall_conn_metric_events)
        .expect("init firewall_conn_metric_events failed");

    // flow match / dns socket map
    flow::init_flow_match_map(&paths.flow_match_map).expect("init flow_match_map failed");
    dns::init_dns_flow_socks(&paths.dns_flow_socks).expect("init dns_flow_socks failed");

    // route: LAN prefix maps and target slots are rebuilt every boot (their
    // content is re-synced from user space anyway).
    route::init_rt4_lan_map(&paths.rt4_lan_map).expect("init rt4_lan_map failed");
    route::init_rt6_lan_map(&paths.rt6_lan_map).expect("init rt6_lan_map failed");
    route::init_rt4_target_slot_map(&paths.rt4_target_slot_map)
        .expect("init rt4_target_slot_map failed");
    route::init_rt6_target_slot_map(&paths.rt6_target_slot_map)
        .expect("init rt6_target_slot_map failed");

    // per-flow rule outers
    flow_dns::init_flow4_dns_map(&paths.flow4_dns_map).expect("init flow4_dns_map failed");
    flow_dns::init_flow6_dns_map(&paths.flow6_dns_map).expect("init flow6_dns_map failed");
    flow_wanip::init_flow4_ip_map(&paths.flow4_ip_map).expect("init flow4_ip_map failed");
    flow_wanip::init_flow6_ip_map(&paths.flow6_ip_map).expect("init flow6_ip_map failed");

    // 每次启动重建 cache 外层 map（含内层 map），避免结构体变更后大小不匹配。
    route::init_rt4_cache_map(&paths.rt4_cache_map, &paths.rt6_cache_map)
        .expect("init rt4/6 cache maps failed");

    // IP <-> MAC + DAD NS events
    mac::init_ip_mac_v4(&paths.ip_mac_v4).expect("init ip_mac_v4 failed");
    mac::init_ip_mac_v6(&paths.ip_mac_v6).expect("init ip_mac_v6 failed");
    mac::init_ip6_dao_events(&paths.ip6_dao_events).expect("init ip6_dao_events failed");

    // XDP redirect ability
    redirect_able::init_xdp_redirect_able(&paths.xdp_redirect_able)
        .expect("init xdp_redirect_able failed");

    route::init_route_wan_cache_inner_map(&paths.rt4_cache_map, &paths.rt6_cache_map);
    route::init_route_lan_cache_inner_map(&paths.rt4_cache_map, &paths.rt6_cache_map);
}

/// Create every shared map at the paths of a caller-provided
/// [`LandscapeMapPath`] (the same layout `LIBBPF_PIN_BY_NAME` skeletons
/// expect under their `pin_root_path`). Integration tests use this to stand
/// up the shared maps inside an isolated bpffs directory before loading the
/// programs under test.
#[cfg(test)]
pub(crate) fn init_maps_for_test(paths: &LandscapeMapPath) {
    wan::init_wan_ip_binding_map(&paths.wan_ip).expect("test init wan_ip_binding");
    nat::init_nat6_static_map(&paths.nat6_static_map).expect("test init nat6_static_map");
    nat::init_nat4_static_map(&paths.nat4_static_map).expect("test init nat4_static_map");
    nat::init_nat_metric_events(&paths.nat_metric_events).expect("test init nat_metric_events");
    firewall::init_firewall_block_ip4_map(&paths.firewall_ipv4_block)
        .expect("test init firewall_block_ip4_map");
    firewall::init_firewall_block_ip6_map(&paths.firewall_ipv6_block)
        .expect("test init firewall_block_ip6_map");
    firewall::init_firewall_conn_metric_events(&paths.firewall_conn_metric_events)
        .expect("test init firewall_conn_metric_events");
    flow::init_flow_match_map(&paths.flow_match_map).expect("test init flow_match_map");
    dns::init_dns_flow_socks(&paths.dns_flow_socks).expect("test init dns_flow_socks");

    route::init_rt4_lan_map(&paths.rt4_lan_map).expect("test init rt4_lan_map");
    route::init_rt6_lan_map(&paths.rt6_lan_map).expect("test init rt6_lan_map");
    route::init_rt4_target_slot_map(&paths.rt4_target_slot_map)
        .expect("test init rt4_target_slot_map");
    route::init_rt6_target_slot_map(&paths.rt6_target_slot_map)
        .expect("test init rt6_target_slot_map");
    flow_dns::init_flow4_dns_map(&paths.flow4_dns_map).expect("test init flow4_dns_map");
    flow_dns::init_flow6_dns_map(&paths.flow6_dns_map).expect("test init flow6_dns_map");
    flow_wanip::init_flow4_ip_map(&paths.flow4_ip_map).expect("test init flow4_ip_map");
    flow_wanip::init_flow6_ip_map(&paths.flow6_ip_map).expect("test init flow6_ip_map");

    route::init_rt4_cache_map(&paths.rt4_cache_map, &paths.rt6_cache_map)
        .expect("test init rt4/6 cache maps");

    mac::init_ip_mac_v4(&paths.ip_mac_v4).expect("test init ip_mac_v4");
    mac::init_ip_mac_v6(&paths.ip_mac_v6).expect("test init ip_mac_v6");
    mac::init_ip6_dao_events(&paths.ip6_dao_events).expect("test init ip6_dao_events");
    redirect_able::init_xdp_redirect_able(&paths.xdp_redirect_able)
        .expect("test init xdp_redirect_able");

    route::init_route_wan_cache_inner_map(&paths.rt4_cache_map, &paths.rt6_cache_map);
    route::init_route_lan_cache_inner_map(&paths.rt4_cache_map, &paths.rt6_cache_map);
}

/// Unpin shared maps during full app shutdown so the kernel can free them.
///
/// Must be called after all services have stopped.
pub fn cleanup_pinned_maps() {
    let maps_to_unpin: [&std::path::Path; 0] = [];
    for path in maps_to_unpin {
        match std::fs::remove_file(path) {
            Ok(()) => tracing::info!("Unpinned map: {}", path.display()),
            Err(e) if e.kind() == std::io::ErrorKind::NotFound => {}
            Err(e) => tracing::warn!("Failed to unpin {}: {e}", path.display()),
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use zerocopy::IntoBytes;

    /// `Default` must yield all-zero bytes: keys built via
    /// `..Default::default()` rely on zeroed padding, and eBPF map lookups
    /// compare the full key — one stray non-zero byte silently misses.
    #[test]
    fn default_keys_are_all_zero() {
        macro_rules! assert_default_zero {
            ($($ty:ty),+ $(,)?) => {$(
                assert!(
                    <$ty as Default>::default().as_bytes().iter().all(|&b| b == 0),
                    concat!(stringify!($ty), ": Default leaves non-zero bytes"),
                );
            )+};
        }

        assert_default_zero!(
            MacKeyV4,
            MacKeyV6,
            WanIpInfoKey,
            Ipv4LpmKey,
            Ipv6LpmKey,
            FlowMatchKey,
            FlowDnsMatchKeyV4,
            FlowDnsMatchKeyV6,
            FlowIpTrieKeyV4,
            FlowIpTrieKeyV6,
            LanRouteKeyV4,
            LanRouteKeyV6,
            RtCacheKeyV4,
            RtCacheKeyV6,
            RouteTargetSlotKeyV4,
            RouteTargetSlotKeyV6,
            NatMappingKeyV4,
            StaticNat6MappingKey,
            Nat4TimerKey,
            Nat6TimerKey,
        );
    }

    // ---------------------------------------------------------------------
    // skeleton-free map creation: create / compatible-reuse / recreate
    // ---------------------------------------------------------------------

    use crate::tests::{ensure_bpffs, isolated_pin_root};

    const TEST_HASH_SPEC: MapCreateSpec = MapCreateSpec {
        map_type: MapType::Hash,
        name: "test_hash_map",
        key_size: 4,
        value_size: 8,
        max_entries: 64,
        map_flags: 0,
        inner: None,
    };

    fn probe_opts() -> libbpf_sys::bpf_map_create_opts {
        libbpf_sys::bpf_map_create_opts {
            sz: std::mem::size_of::<libbpf_sys::bpf_map_create_opts>() as libbpf_sys::size_t,
            ..Default::default()
        }
    }

    /// Create a map under an isolated pin root; skip when the environment
    /// cannot create BPF maps (no CAP_BPF etc.).
    fn run_or_skip<T>(name: &str, f: impl FnOnce(&Path) -> T) -> Option<T> {
        ensure_bpffs();
        let root = isolated_pin_root(name);
        // Probe privilege once by creating a throwaway map handle.
        match MapHandle::create(MapType::Hash, None::<&str>, 4, 4, 1, &probe_opts()) {
            Ok(_) => Some(f(&root)),
            Err(e) => {
                eprintln!("skipping `{name}`: cannot create BPF maps: {e:?}");
                None
            }
        }
    }

    #[test]
    fn ensure_pinned_map_creates_then_reuses_compatible() {
        let Some(m) = run_or_skip("init-map-create-reuse", |root| {
            let pin = root.join("test_hash_map");

            let first = ensure_pinned_map(&TEST_HASH_SPEC, &pin).expect("create");
            first.update(&1u32.to_ne_bytes(), &1u64.to_ne_bytes(), MapFlags::ANY).expect("seed");
            drop(first);

            // Second call must reuse the pinned map (data preserved, file kept).
            let second = ensure_pinned_map(&TEST_HASH_SPEC, &pin).expect("reuse");
            let value = second
                .lookup(&1u32.to_ne_bytes(), MapFlags::ANY)
                .expect("lookup after reuse")
                .expect("entry must survive a compatible reuse");
            assert_eq!(value, 1u64.to_ne_bytes(), "compatible reuse must keep entries");
            pin
        }) else {
            return;
        };
        let _ = m;
    }

    #[test]
    fn recreate_pinned_map_drops_data_and_replaces() {
        let Some(_) = run_or_skip("init-map-recreate", |root| {
            let pin = root.join("test_hash_map");

            let first = recreate_pinned_map(&TEST_HASH_SPEC, &pin).expect("create");
            first.update(&1u32.to_ne_bytes(), &1u64.to_ne_bytes(), MapFlags::ANY).expect("seed");
            drop(first);

            // Recreate must remove the old pin file and start empty.
            let second = recreate_pinned_map(&TEST_HASH_SPEC, &pin).expect("recreate");
            assert!(
                second
                    .lookup(&1u32.to_ne_bytes(), MapFlags::ANY)
                    .expect("lookup after recreate")
                    .is_none(),
                "recreate must drop existing entries"
            );
        }) else {
            return;
        };
    }

    #[test]
    fn ensure_pinned_map_recreates_on_param_drift() {
        let Some(_) = run_or_skip("init-map-drift", |root| {
            let pin = root.join("test_hash_map");

            let first = ensure_pinned_map(&TEST_HASH_SPEC, &pin).expect("create");
            first.update(&1u32.to_ne_bytes(), &1u64.to_ne_bytes(), MapFlags::ANY).expect("seed");
            drop(first);

            // A spec whose max_entries changed must trigger a recreate.
            let drifted = MapCreateSpec { max_entries: 128, ..TEST_HASH_SPEC };
            let second = ensure_pinned_map(&drifted, &pin).expect("recreate on drift");
            assert!(
                second
                    .lookup(&1u32.to_ne_bytes(), MapFlags::ANY)
                    .expect("lookup after drift")
                    .is_none(),
                "layout drift must drop stale entries"
            );
        }) else {
            return;
        };
    }

    #[test]
    fn wrong_layout_pinned_map_is_detected_and_recreated() {
        let Some(_) = run_or_skip("init-map-wrong-layout", |root| {
            let pin = root.join("test_hash_map");

            // Simulate a stale/foreign pinned map with a mismatched layout.
            let mut wrong =
                MapHandle::create(MapType::Hash, Some("test_hash_map"), 4, 4, 64, &probe_opts())
                    .expect("create wrong-layout map");
            wrong.pin(&pin).expect("pin wrong-layout map");
            wrong.update(&1u32.to_ne_bytes(), &1u32.to_ne_bytes(), MapFlags::ANY).expect("seed");
            drop(wrong);

            // ensure_pinned_map expects value_size 8; the 4-byte pinned map must
            // be detected as incompatible and rebuilt with the correct layout.
            let map = ensure_pinned_map(&TEST_HASH_SPEC, &pin).expect("recreate on wrong layout");
            let info = libbpf_rs::MapInfo::new(map.as_fd()).expect("map info");
            assert_eq!(info.info.value_size, TEST_HASH_SPEC.value_size);
            assert!(
                map.lookup(&1u32.to_ne_bytes(), MapFlags::ANY).expect("lookup").is_none(),
                "stale entry must be dropped on layout recreate"
            );
        }) else {
            return;
        };
    }

    #[test]
    fn ensure_pinned_map_recreates_on_value_size_drift() {
        let Some(_) = run_or_skip("init-map-value-size-drift", |root| {
            let pin = root.join("test_hash_map");

            let first = ensure_pinned_map(&TEST_HASH_SPEC, &pin).expect("create");
            first.update(&1u32.to_ne_bytes(), &1u64.to_ne_bytes(), MapFlags::ANY).expect("seed");
            drop(first);

            let drifted = MapCreateSpec { value_size: 16, ..TEST_HASH_SPEC };
            let second = ensure_pinned_map(&drifted, &pin).expect("recreate on value-size drift");
            let info = libbpf_rs::MapInfo::new(second.as_fd()).expect("info");
            assert_eq!(info.info.value_size, 16);
            assert!(
                second.lookup(&1u32.to_ne_bytes(), MapFlags::ANY).expect("lookup").is_none(),
                "value-size drift must drop stale entries"
            );
        }) else {
            return;
        };
    }

    #[test]
    fn ensure_pinned_map_recreates_on_map_flags_drift() {
        let Some(_) = run_or_skip("init-map-flags-drift", |root| {
            let pin = root.join("test_hash_map");

            let first = ensure_pinned_map(&TEST_HASH_SPEC, &pin).expect("create");
            first.update(&1u32.to_ne_bytes(), &1u64.to_ne_bytes(), MapFlags::ANY).expect("seed");
            drop(first);

            let drifted = MapCreateSpec {
                map_flags: libbpf_sys::BPF_F_NO_PREALLOC,
                ..TEST_HASH_SPEC
            };
            let second = ensure_pinned_map(&drifted, &pin).expect("recreate on flags drift");
            let info = libbpf_rs::MapInfo::new(second.as_fd()).expect("info");
            assert_eq!(info.info.map_flags, libbpf_sys::BPF_F_NO_PREALLOC);
            assert!(
                second.lookup(&1u32.to_ne_bytes(), MapFlags::ANY).expect("lookup").is_none(),
                "flags drift must drop stale entries"
            );
        }) else {
            return;
        };
    }

    #[test]
    fn ensure_pinned_map_recreates_on_map_type_drift() {
        let Some(_) = run_or_skip("init-map-type-drift", |root| {
            let pin = root.join("test_hash_map");

            let first = ensure_pinned_map(&TEST_HASH_SPEC, &pin).expect("create");
            first.update(&1u32.to_ne_bytes(), &1u64.to_ne_bytes(), MapFlags::ANY).expect("seed");
            drop(first);

            let drifted = MapCreateSpec { map_type: MapType::LruHash, ..TEST_HASH_SPEC };
            let second = ensure_pinned_map(&drifted, &pin).expect("recreate on type drift");
            let info = libbpf_rs::MapInfo::new(second.as_fd()).expect("info");
            assert_eq!(info.map_type(), MapType::LruHash);
            assert!(
                second.lookup(&1u32.to_ne_bytes(), MapFlags::ANY).expect("lookup").is_none(),
                "type drift must drop stale entries"
            );
        }) else {
            return;
        };
    }

    #[test]
    fn map_in_map_outer_is_never_silently_reused() {
        let Some(_) = run_or_skip("init-map-in-map-no-reuse", |root| {
            let inner = InnerMapSpec {
                map_type: MapType::LruHash,
                name: "test_inner",
                key_size: 4,
                value_size: 8,
                max_entries: 16,
                map_flags: 0,
            };
            let spec = MapCreateSpec {
                map_type: MapType::HashOfMaps,
                name: "test_outer",
                key_size: 4,
                value_size: 4,
                max_entries: 8,
                map_flags: 0,
                inner: Some(inner),
            };
            let pin = root.join("test_outer");

            // Create once and bind a real inner map to slot 7.
            let outer = ensure_pinned_map(&spec, &pin).expect("create outer");
            let inner_map =
                MapHandle::create(MapType::LruHash, None::<&str>, 4, 8, 16, &probe_opts())
                    .expect("create inner");
            let fd = inner_map.as_fd().as_raw_fd().to_ne_bytes();
            outer.update(&7u32.to_ne_bytes(), &fd, MapFlags::ANY).expect("attach inner");
            drop((outer, inner_map));

            // A map-in-map outer is never trusted for reuse, so the identical
            // spec must still rebuild the outer and drop the bound inner map.
            let outer2 = ensure_pinned_map(&spec, &pin).expect("recreate outer");
            assert!(
                outer2.lookup(&7u32.to_ne_bytes(), MapFlags::ANY).expect("lookup").is_none(),
                "map-in-map outer must be recreated, dropping the bound inner map"
            );
        }) else {
            return;
        };
    }

    #[test]
    fn ensure_pinned_map_creates_map_in_map_outer() {
        let Some(_) = run_or_skip("init-map-in-map", |root| {
            let inner = InnerMapSpec {
                map_type: MapType::LruHash,
                name: "test_inner",
                key_size: 4,
                value_size: 8,
                max_entries: 16,
                map_flags: 0,
            };
            let spec = MapCreateSpec {
                map_type: MapType::HashOfMaps,
                name: "test_outer",
                key_size: 4,
                value_size: 4,
                max_entries: 8,
                map_flags: 0,
                inner: Some(inner),
            };

            let pin = root.join("test_outer");
            let outer = ensure_pinned_map(&spec, &pin).expect("create map-in-map");

            // The kernel must accept an inner LRU_HASH of the template's layout.
            let probe = libbpf_sys::bpf_map_create_opts {
                sz: std::mem::size_of::<libbpf_sys::bpf_map_create_opts>() as libbpf_sys::size_t,
                ..Default::default()
            };
            let inner_map = MapHandle::create(
                MapType::LruHash,
                None::<&str>,
                inner.key_size,
                inner.value_size,
                inner.max_entries,
                &probe,
            )
            .expect("create inner map");
            let fd = inner_map.as_fd().as_raw_fd().to_ne_bytes();
            outer.update(&7u32.to_ne_bytes(), &fd, MapFlags::ANY).expect("attach inner map");

            let info = libbpf_rs::MapInfo::new(outer.as_fd()).expect("outer info");
            assert_eq!(info.map_type(), MapType::HashOfMaps, "outer must be hash-of-maps");
        }) else {
            return;
        };
    }

    #[test]
    fn ensure_pinned_map_creates_ringbuf() {
        let Some(_) = run_or_skip("init-ringbuf", |root| {
            let spec = MapCreateSpec {
                map_type: MapType::RingBuf,
                name: "test_ringbuf",
                key_size: 0,
                value_size: 0,
                max_entries: 4096,
                map_flags: 0,
                inner: None,
            };
            let pin = root.join("test_ringbuf");
            let map = ensure_pinned_map(&spec, &pin).expect("create ringbuf");
            let info = libbpf_rs::MapInfo::new(map.as_fd()).expect("ringbuf info");
            assert_eq!(info.map_type(), MapType::RingBuf, "must be a ringbuf");
        }) else {
            return;
        };
    }

    // ---------------------------------------------------------------------
    // negative/layout-drift guards: a wrong spec must be rejected by the
    // skel comparison (no BPF required, always runs)
    // ---------------------------------------------------------------------

    #[test]
    #[should_panic(expected = "value size drift")]
    fn spec_rejects_wrong_value_size() {
        use libbpf_rs::skel::SkelBuilder as _;
        let mut obj = std::mem::MaybeUninit::uninit();
        let open = crate::stages::nat::xdp_nat_skel::XdpNatSkelBuilder::default()
            .open(&mut obj)
            .expect("open anchor skel");
        let spec = crate::maps::wan::WAN_IP_BINDING_SPEC;
        let wrong = MapCreateSpec { value_size: spec.value_size + 1, ..spec };
        crate::maps::assert_skel_map_matches(&open.maps.wan_ip_binding, &wrong);
    }

    #[test]
    #[should_panic(expected = "inner value size drift")]
    fn spec_rejects_inner_value_size_drift() {
        use libbpf_rs::skel::SkelBuilder as _;
        let mut obj = std::mem::MaybeUninit::uninit();
        let open =
            crate::chain::xdp_wan_route::xdp_wan_route_skel::XdpWanRouteSkelBuilder::default()
                .open(&mut obj)
                .expect("open anchor skel");
        let spec = crate::maps::route::RT4_CACHE_MAP_SPEC;
        let inner = spec.inner.expect("cache outer has an inner template");
        let wrong = MapCreateSpec {
            inner: Some(InnerMapSpec { value_size: inner.value_size + 1, ..inner }),
            ..spec
        };
        crate::maps::assert_skel_map_matches(&open.maps.rt4_cache_map, &wrong);
    }

    #[test]
    #[should_panic(expected = "the C definition is a map-in-map")]
    fn spec_rejects_missing_inner_for_map_in_map() {
        use libbpf_rs::skel::SkelBuilder as _;
        let mut obj = std::mem::MaybeUninit::uninit();
        let open =
            crate::chain::xdp_wan_route::xdp_wan_route_skel::XdpWanRouteSkelBuilder::default()
                .open(&mut obj)
                .expect("open anchor skel");
        let spec = crate::maps::route::RT4_CACHE_MAP_SPEC;
        let wrong = MapCreateSpec { inner: None, ..spec };
        crate::maps::assert_skel_map_matches(&open.maps.rt4_cache_map, &wrong);
    }

    #[test]
    #[should_panic(expected = "type drift")]
    fn spec_rejects_wrong_map_type() {
        use libbpf_rs::skel::SkelBuilder as _;
        let mut obj = std::mem::MaybeUninit::uninit();
        let open =
            crate::chain::xdp_wan_route::xdp_wan_route_skel::XdpWanRouteSkelBuilder::default()
                .open(&mut obj)
                .expect("open anchor skel");
        let spec = crate::maps::route::RT4_LAN_MAP_SPEC;
        let wrong = MapCreateSpec { map_type: MapType::Hash, ..spec };
        crate::maps::assert_skel_map_matches(&open.maps.rt4_lan_map, &wrong);
    }

    /// The production orchestrator: run the full `init_path` against a
    /// temporary pin root, then run it again and prove that persistent maps
    /// keep their data while per-boot maps are rebuilt empty.
    #[test]
    fn init_path_creates_all_maps_and_reuses_on_restart() {
        use crate::maps::{
            dns, firewall, flow, flow_dns, flow_wanip, mac, nat, redirect_able, route, wan,
        };
        use crate::LandscapeMapPath;

        let Some(_) = run_or_skip("init-path", |root| {
            let paths = LandscapeMapPath::from_root(root);

            init_path(&paths);
            for name in [
                wan::WAN_IP_BINDING_PIN,
                nat::NAT4_STATIC_MAP_PIN,
                nat::NAT6_STATIC_MAP_PIN,
                firewall::FIREWALL_BLOCK_IP4_MAP_PIN,
                firewall::FIREWALL_BLOCK_IP6_MAP_PIN,
                flow::FLOW_MATCH_MAP_PIN,
                dns::DNS_FLOW_SOCKS_PIN,
                nat::NAT_METRIC_EVENTS_PIN,
                firewall::FIREWALL_CONN_METRIC_EVENTS_PIN,
                route::RT4_LAN_MAP_PIN,
                route::RT6_LAN_MAP_PIN,
                route::RT4_TARGET_SLOT_MAP_PIN,
                route::RT6_TARGET_SLOT_MAP_PIN,
                flow_dns::FLOW4_DNS_MAP_PIN,
                flow_wanip::FLOW4_IP_MAP_PIN,
                flow_dns::FLOW6_DNS_MAP_PIN,
                flow_wanip::FLOW6_IP_MAP_PIN,
                route::RT4_CACHE_MAP_PIN,
                route::RT6_CACHE_MAP_PIN,
                mac::IP_MAC_V4_PIN,
                mac::IP_MAC_V6_PIN,
                mac::IP6_DAO_EVENTS_PIN,
                redirect_able::XDP_REDIRECT_ABLE_PIN,
            ] {
                assert!(root.join(name).exists(), "missing pin file {name}");
            }

            // Seed a persistent map (nat4 static survives restarts).
            let nat4 =
                libbpf_rs::MapHandle::from_pinned_path(&paths.nat4_static_map).expect("open nat4");
            let key = [1u8; 8];
            nat4.update(&key, &[2u8; 8], MapFlags::ANY).expect("seed nat4 static");

            // Second "boot": persistent data must survive, per-boot maps reset.
            init_path(&paths);
            let nat4 =
                libbpf_rs::MapHandle::from_pinned_path(&paths.nat4_static_map).expect("open nat4");
            assert!(
                nat4.lookup(&key, MapFlags::ANY).expect("lookup").is_some(),
                "persistent map data must survive a restart"
            );
            let rt4_cache = libbpf_rs::MapHandle::from_pinned_path(&paths.rt4_cache_map)
                .expect("open rt4_cache");
            let inner_id = rt4_cache.lookup(&0u32.to_ne_bytes(), MapFlags::ANY).expect("lookup");
            assert!(inner_id.is_some(), "cache outer must be repopulated with inner maps");
        }) else {
            return;
        };
    }
}
