services:
  landscap:
    image: landscape:x86_64
    container_name: land_rt
    privileged: true
    pull_policy: if_not_present
    environment:
      LANDSCAPE_EBPF_MAP_SPACE: docker
    volumes:
      - ./landscape_init.toml:/root/.landscape-router/landscape_init.toml
      - /sys/fs/bpf/docker/:/sys/fs/bpf/
    networks:
      out:
        ipv4_address: 172.123.0.2

  firefox:
    container_name: land_ff
    image: jlesage/firefox
    environment:
      LANG: zh_CN.UTF-8
      FF_OPEN_URL: "http://land_rt:6300"
      ENABLE_CJK_FONT: 1
    dns:
      - 1.1.1.1
    ports:
      - "5800:5800"
    networks:
      out:
        ipv4_address: 172.123.0.3

networks:
  out:
    driver: bridge
    ipam:
      config:
        - subnet: 172.123.0.0/16
          gateway: 172.123.0.1

