[package]
name = "landscape-common"
version.workspace = true
edition.workspace = true

[dependencies]
serde = { workspace = true }
clap = { workspace = true }
serde_json = { workspace = true }
once_cell = { workspace = true }
sysinfo = { workspace = true }
tokio = { workspace = true, features = ["full"] }
