[package]
name = "landscape-metric"
version.workspace = true
edition.workspace = true

[dependencies]
landscape-common = { path = "../landscape-common" }
landscape-core = { path = "../landscape-core" }

tokio = { workspace = true, features = ["sync", "time", "rt", "rt-multi-thread"] }
tokio-util = { workspace = true, features = ["rt"] }
tracing = { workspace = true }
serde_json = { workspace = true }

sqlx = { workspace = true, optional = true }
futures-util = { workspace = true, optional = true }
hdrhistogram = { workspace = true, optional = true }

[features]
default = []
metric-persistent = ["dep:sqlx", "dep:futures-util", "dep:hdrhistogram"]

[dev-dependencies]
tempfile = { workspace = true }
tokio = { workspace = true, features = ["macros", "test-util"] }
tracing-appender = { workspace = true }
tracing-subscriber = { workspace = true, features = ["env-filter"] }
