pub mod pty;

/// All domain errors implement this trait to provide error_id and HTTP status code.
pub trait LdApiErrorInfo {
    fn error_id(&self) -> &'static str;
    fn http_status_code(&self) -> u16;
    fn error_args(&self) -> serde_json::Value {
        serde_json::json!({})
    }
    /// Public-safe message; override to hide internal details. Defaults to the
    /// Display text. Transparent delegate variants generated by `#[derive(LdApiError)]`
    /// forward to the wrapped error's `to_public_message`.
    fn to_public_message(&self) -> String
    where
        Self: std::fmt::Display,
    {
        self.to_string()
    }
}
